name: Pipeline Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.SSH_PRIVATE_KEY  }} > private_key && chmod 600 private_key
      - name: Despliegue en la instancia aws
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: private_key
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
